-- MySQL Script generated by MySQL Workbench
-- Wed Jun  1 12:18:13 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizzeria` DEFAULT CHARACTER SET utf8 ;
USE `pizzeria` ;

-- -----------------------------------------------------
-- Table `pizzeria`.`provincias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`provincias` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`localidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`localidades` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `provincias_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_localidades_provincias_idx` (`provincias_id` ASC) VISIBLE,
  CONSTRAINT `fk_localidades_provincias`
    FOREIGN KEY (`provincias_id`)
    REFERENCES `pizzeria`.`provincias` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NULL,
  `codigo_postal` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `provincias_id` INT NOT NULL,
  `localidades_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_clientes_provincias1_idx` (`provincias_id` ASC) VISIBLE,
  INDEX `fk_clientes_localidades1_idx` (`localidades_id` ASC) VISIBLE,
  CONSTRAINT `fk_clientes_provincias1`
    FOREIGN KEY (`provincias_id`)
    REFERENCES `pizzeria`.`provincias` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_clientes_localidades1`
    FOREIGN KEY (`localidades_id`)
    REFERENCES `pizzeria`.`localidades` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`tiendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`tiendas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(45) NULL,
  `codigo_postal` VARCHAR(45) NULL,
  `provincias_id` INT NOT NULL,
  `localidades_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tiendas_provincias1_idx` (`provincias_id` ASC) VISIBLE,
  INDEX `fk_tiendas_localidades1_idx` (`localidades_id` ASC) VISIBLE,
  CONSTRAINT `fk_tiendas_provincias1`
    FOREIGN KEY (`provincias_id`)
    REFERENCES `pizzeria`.`provincias` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tiendas_localidades1`
    FOREIGN KEY (`localidades_id`)
    REFERENCES `pizzeria`.`localidades` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`pedidos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` ENUM('DOMICILIO', 'RECOGIDA') NULL,
  `fecha` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `total_pizzas` INT NULL,
  `total_hamburguesas` INT NULL,
  `total_bebidas` INT NULL,
  `precio_total` DECIMAL NULL,
  `clientes_id` INT NOT NULL,
  `tiendas_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pedidos_clientes1_idx` (`clientes_id` ASC) VISIBLE,
  INDEX `fk_pedidos_tiendas1_idx` (`tiendas_id` ASC) VISIBLE,
  CONSTRAINT `fk_pedidos_clientes1`
    FOREIGN KEY (`clientes_id`)
    REFERENCES `pizzeria`.`clientes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pedidos_tiendas1`
    FOREIGN KEY (`tiendas_id`)
    REFERENCES `pizzeria`.`tiendas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`hamburguesas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`hamburguesas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(100) NULL,
  `imagen` BLOB NOT NULL,
  `precio` DECIMAL NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`categorias_pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`categorias_pizza` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`pizzas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`pizzas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(100) NULL,
  `imagen` VARCHAR(255) NOT NULL,
  `precio` DECIMAL NOT NULL,
  `categorias_pizza_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pizzas_categorias_pizza1_idx` (`categorias_pizza_id` ASC) VISIBLE,
  CONSTRAINT `fk_pizzas_categorias_pizza1`
    FOREIGN KEY (`categorias_pizza_id`)
    REFERENCES `pizzeria`.`categorias_pizza` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`bebidas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`bebidas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(100) NULL,
  `imagen` VARCHAR(255) NOT NULL,
  `precio` DECIMAL NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`pedidos_has_hamburguesas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`pedidos_has_hamburguesas` (
  `pedidos_id` INT NOT NULL,
  `pedidos_clientes_id` INT NOT NULL,
  `hamburguesas_id` INT NOT NULL,
  PRIMARY KEY (`pedidos_id`, `pedidos_clientes_id`, `hamburguesas_id`),
  INDEX `fk_pedidos_has_hamburguesas_hamburguesas1_idx` (`hamburguesas_id` ASC) VISIBLE,
  INDEX `fk_pedidos_has_hamburguesas_pedidos1_idx` (`pedidos_id` ASC, `pedidos_clientes_id` ASC) VISIBLE,
  CONSTRAINT `fk_pedidos_has_hamburguesas_pedidos1`
    FOREIGN KEY (`pedidos_id` , `pedidos_clientes_id`)
    REFERENCES `pizzeria`.`pedidos` (`id` , `clientes_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pedidos_has_hamburguesas_hamburguesas1`
    FOREIGN KEY (`hamburguesas_id`)
    REFERENCES `pizzeria`.`hamburguesas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`pedidos_has_pizzas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`pedidos_has_pizzas` (
  `pedidos_id` INT NOT NULL,
  `pedidos_clientes_id` INT NOT NULL,
  `pizzas_id` INT NOT NULL,
  PRIMARY KEY (`pedidos_id`, `pedidos_clientes_id`, `pizzas_id`),
  INDEX `fk_pedidos_has_pizzas_pizzas1_idx` (`pizzas_id` ASC) VISIBLE,
  INDEX `fk_pedidos_has_pizzas_pedidos1_idx` (`pedidos_id` ASC, `pedidos_clientes_id` ASC) VISIBLE,
  CONSTRAINT `fk_pedidos_has_pizzas_pedidos1`
    FOREIGN KEY (`pedidos_id` , `pedidos_clientes_id`)
    REFERENCES `pizzeria`.`pedidos` (`id` , `clientes_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pedidos_has_pizzas_pizzas1`
    FOREIGN KEY (`pizzas_id`)
    REFERENCES `pizzeria`.`pizzas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`pedidos_has_bebidas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`pedidos_has_bebidas` (
  `pedidos_id` INT NOT NULL,
  `pedidos_clientes_id` INT NOT NULL,
  `bebidas_id` INT NOT NULL,
  PRIMARY KEY (`pedidos_id`, `pedidos_clientes_id`, `bebidas_id`),
  INDEX `fk_pedidos_has_bebidas_bebidas1_idx` (`bebidas_id` ASC) VISIBLE,
  INDEX `fk_pedidos_has_bebidas_pedidos1_idx` (`pedidos_id` ASC, `pedidos_clientes_id` ASC) VISIBLE,
  CONSTRAINT `fk_pedidos_has_bebidas_pedidos1`
    FOREIGN KEY (`pedidos_id` , `pedidos_clientes_id`)
    REFERENCES `pizzeria`.`pedidos` (`id` , `clientes_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pedidos_has_bebidas_bebidas1`
    FOREIGN KEY (`bebidas_id`)
    REFERENCES `pizzeria`.`bebidas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`empleados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `nif` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `puesto` ENUM('Repartidor', 'Cocinero') NULL,
  `tiendas_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_empleados_tiendas1_idx` (`tiendas_id` ASC) VISIBLE,
  CONSTRAINT `fk_empleados_tiendas1`
    FOREIGN KEY (`tiendas_id`)
    REFERENCES `pizzeria`.`tiendas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`pedidos_domicilio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`pedidos_domicilio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_repartidor` INT NULL,
  `id_pedido` INT NULL,
  `fecha_entrega` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_pedidos_domicilio_repartidor_idx` (`id_repartidor` ASC) VISIBLE,
  INDEX `fk_pedidos_domicilio_pedido_idx` (`id_pedido` ASC) VISIBLE,
  CONSTRAINT `fk_pedidos_domicilio_repartidor`
    FOREIGN KEY (`id_repartidor`)
    REFERENCES `pizzeria`.`empleados` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pedidos_domicilio_pedido`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `pizzeria`.`pedidos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
