-- MySQL Script generated by MySQL Workbench
-- Wed Jun  1 14:57:03 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema optica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema optica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `optica` DEFAULT CHARACTER SET utf8 ;
USE `optica` ;

-- -----------------------------------------------------
-- Table `optica`.`direcciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`direcciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `calle` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(10) NOT NULL,
  `piso` VARCHAR(10) NULL,
  `puerta` VARCHAR(2) NULL,
  `codigo_postal` VARCHAR(5) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optica`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`proveedores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(12) NULL,
  `fax` VARCHAR(12) NULL,
  `nif` VARCHAR(9) NOT NULL,
  `direcciones_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_proveedores_direcciones1_idx` (`direcciones_id` ASC) VISIBLE,
  CONSTRAINT `fk_proveedores_direcciones1`
    FOREIGN KEY (`direcciones_id`)
    REFERENCES `optica`.`direcciones` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optica`.`vendedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`vendedores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optica`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NULL,
  `email` VARCHAR(255) NULL,
  `fecha_registro` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `id_cliente_recomendador` INT NULL,
  `direcciones_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_cliente_recomendador_idx` (`id_cliente_recomendador` ASC) VISIBLE,
  INDEX `fk_clientes_direcciones1_idx` (`direcciones_id` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_recomendador`
    FOREIGN KEY (`id_cliente_recomendador`)
    REFERENCES `optica`.`clientes` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_clientes_direcciones1`
    FOREIGN KEY (`direcciones_id`)
    REFERENCES `optica`.`direcciones` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optica`.`gafas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`gafas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(45) NOT NULL,
  `graduacion_izquierda` DECIMAL NOT NULL,
  `graduacion_derecha` DECIMAL NOT NULL,
  `color_montura` VARCHAR(45) NULL,
  `color_vidrio_izquierda` VARCHAR(45) NULL,
  `color_vidrio_derecha` VARCHAR(45) NULL,
  `precio` DECIMAL NOT NULL,
  `proveedores_id` INT NOT NULL,
  `vendedores_id` INT NOT NULL,
  `clientes_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_gafas_proveedores1_idx` (`proveedores_id` ASC) VISIBLE,
  INDEX `fk_gafas_vendedores1_idx` (`vendedores_id` ASC) VISIBLE,
  INDEX `fk_gafas_clientes1_idx` (`clientes_id` ASC) VISIBLE,
  CONSTRAINT `fk_gafas_proveedores1`
    FOREIGN KEY (`proveedores_id`)
    REFERENCES `optica`.`proveedores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_gafas_vendedores1`
    FOREIGN KEY (`vendedores_id`)
    REFERENCES `optica`.`vendedores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_gafas_clientes1`
    FOREIGN KEY (`clientes_id`)
    REFERENCES `optica`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
